### ISSUE TITLE
Question regarding the Docs and Enigma VB

### ISSUE THREAD

**Issue by bendulum** [etiktin/node-generate-evb#1]
First off, thanks for creating this package. I have a question regarding its usage.
I use electron and electron-packager to bundle my app.
The output directory contains a couple of dll files, locales and resources folders, .. and MyApp.exe which I can start the app with, which works fine.
I have managed to create an installer from this directory using Inno Setup. Everything works fine this way as well.
However, I'm trying to create a single portable executable now from that directory using Enigma Virtual Box. For that I'm using the enigmavirtualbox package and your generate-evb package. Unfortunately I get an error message when trying to open the final .exe: `Cannot find function ordinal 345 in library COMCTL32.dll`

``` javascript
var generateEvb = require('generate-evb');
var evb = path.resolve('./builds/windows/app.evb');
var exe = path.resolve('./builds/windows/MyAppBundled/MyApp.exe');
var result = path.resolve('./portable/MyApp.exe');
var input = path.resolve('./builds/windows/MyAppBundled');
generateEvb(evb, exe, result, input);
```

My questions is regarding the docs: _inputExe (String) - the input executable file path. Enigma packs the files from path2pack into a copy of this exe_
Does this mean that my `path2pack` directory must not contain the `inputExe` itself, which it does in my case? Is Enigma trying to copy my exe file into itself? How would I circumvent this?

This is probably not a problem with this package, but I thought you might have an idea! Thanks.

**Comment by bendulum** [comment]
I think I answered my own question. I stop getting these weird errors when moving "MyApp.exe" out of the "MyAppBundled" directory before packing with Enigma. One problem remains, when moving the resulting single executable around it stops working, which might be due to absolute paths being used..

**Comment by etiktin** [comment]
Hi @bendulum, glad you find it useful :)

> Does this mean that my path2pack directory must not contain the inputExe itself, which it does in my case?

Yes, you need to make sure that the `inputExe` is not in the `path2pack`. The way to do that currently is to copy the entire folder some where else without the `inputExe` and use that as your `path2pack`. To make it easier in the future, I'll add support for a filter callback.

Another thing to consider is that you don't need an asar when using EVB. So instead of holding your app specific code in `app.asar`, you should hold it in an `app` folder.

> One problem remains, when moving the resulting single executable around it stops working, which might be due to absolute paths being used..

That's odd. I just tried to create a packed Electron app myself and it works fine when moved. What happens when you try to run it? If you don't see an exception, try to run it from cmd and maybe it will print something to the console.

**Comment by bendulum** [comment]
@etiktin Thank you for the quick reply and your feedback! I have "asar" packing already disabled in my electron-packager config, so that should be fine. As soon as I have time I will try again with moving the `path2pack` directory without the `inputExe`. I will report back thereafter!
PS: I just found this [issue](https://github.com/atom/electron/issues/914) not sure if it could be related.

**Comment by bendulum** [comment]
It works as you described, thanks. Also, moving the final executable around does not break it anymore.

**Comment by etiktin** [comment]
@bendulum, I released a new version of [generate-evb](https://www.npmjs.com/package/generate-evb), with support for a filter function. So `inputExe` can be in `path2Pack` and you can just filter it out.

**Comment by bendulum** [comment]
Awesome, I will try this as soon as I get the chance!

**Comment by matthiasg** [comment]
@bendulum is this still working for you ? I cannot get EVB to work with electron 0.35.0 

`[30744:1118/135748:FATAL:scoped_handle.cc(184)] Check failed: 0U != (flags & 0x00000002) (0 vs. 0)`

**Comment by etiktin** [comment]
@matthiasg it works for me with Electron v0.35.1. I packed Electron's folder, and when I execute, it opens the default app as usual.
Things to check:
- Make sure you don't pack `inputExe` in the `path2pack` (you can use a filter function to filter electron.exe out).
- Don't pack you're app files with `asar`. It's redundant and might cause issues.
- Make sure you're code doesn't try to write to your app folder.

**Comment by matthiasg** [comment]
i left the inputExe out (i dragged it in manually leaving the exe out), i will check whether an asar file was created.

i dont have an app loaded yet (its just an index.html plus mini-main to open it) and it doesnt want to write anywhere, but good to know.
