### ISSUE TITLE
Why ucs2 charset?

### ISSUE THREAD

**Issue by frank-dspeed** [etiktin/node-generate-evb#10]
Is there a reason for that JS normaly produces utf 8 and you wrote about the BOM which also indicates utf8 so why ucs2?

**Comment by etiktin** [comment]
@frank-dspeed I assume you're talking about the following lines:
https://github.com/etiktin/generate-evb/blob/96be436b1e6f27c5e17be3b172580ae3523c6923/index.js#L203-L208
As far as I remember (I wrote this code years ago), the project files created by the EVB GUI were encoded in UTF16 and included a BOM. This encoding is also declared at the beginning of the file (XML encoding declaration). So inorder to prevent compatibility issues with future versions of EVB, we also encode the project files we generate as UTF16 (note that the UCS2 encoding in Node.js is actually an alias to UTF16LE).

While working on this (at the time), I noticed that EVB didn't really care about the BOM (either their XML reader assumes it's UTF16 or it's smart enough to figure it out). Also note that adding BOM in Node.js felt a bit hacky (prepending the BOM manually to the buffer). So I decided to not add the BOM, but left a comment with the details in case this will ever become an issue.
