### ISSUE TITLE
Exe is not as compressed as when done through actual Enigma product

### ISSUE THREAD

**Issue by mayur-bhatkhande** [etiktin/node-generate-evb#3]
Hello,
This is really great package and very helpful for us.
We are generating NW build using maven-grunt and then using this generate-evb package to create a single exe of the NW build directory.
If we use actual product to do this we get exe of size NOT more than 150 MB.
But when generated through generate-evb, it settles around 285 MB.
Original build folder is 390 MB.
Can something be done about it?

**Comment by etiktin** [comment]
Hi @mayur-bhatkhande,
To figure out the cause, I suggest you compare the project file (*.evb) generated by `generate-evb` and the project file created using EVB's GUI. You can compare them using a diff tool, or by loading the generated project file in EVB's GUI to see if something looks off.

Maybe you are packing more files in the generated project file (e.g. your `path2Pack`  includes the `inputExe`, which would pack it twice). If that is the case, you can solve it by supplying a filter function (there's an example in the [README](https://github.com/etiktin/generate-evb/blob/59210bb961660aca3dcfbc3368cf85aa817e5996/README.md)).
